# force_cleanup() {
#     log_info "강제 컨테이너 정리 중..."
#     docker stop llm-agent vector-search curriculum tool-sql department-mapping llm-client 2>/dev/null || true
#     docker rm -f llm-agent vector-search curriculum tool-sql department-mapping llm-client 2>/dev/null || true
#     docker network prune -f 2>/dev/null || true
# }

version: '3.3'

services:
  curriculum:
    build:
      context: ./ai_modules/curriculum-main
      dockerfile: Dockerfile
    container_name: curriculum
    environment:
      - PORT=7996
      - TZ=Asia/Seoul
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=3311
      - DB_USER=root
      - DB_NAME=nll_third
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "7996:7996"
    restart: unless-stopped

  vector-search:
    build:
      context: ./ai_modules/faiss_search-main
      dockerfile: Dockerfile
    container_name: vector-search
    environment:
      - PORT=7997
      - TZ=Asia/Seoul
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=3313
      - DB_USER=root
      - DB_NAME=nll_third
      - DB_PASSWORD=${DB_PASSWORD}
      - VECTOR_DB_PASSWORD=${VECTOR_DB_PASSWORD}
    volumes:
      - ./ai_modules/faiss_search-main/logs:/app/logs
      - ./ai_modules/faiss_search-main/service:/app/service
      - ./ai_modules/faiss_search-main/util:/app/util
      - ./ai_modules/faiss_search-main/prompts:/app/prompts
    ports:
      - "7997:7997"
    restart: unless-stopped

  llm_agent:
    build:
      context: ./ai_modules/llm_agent-main
      dockerfile: Dockerfile
    container_name: llm-agent
    environment:
      - PORT=8001
      - TZ=Asia/Seoul
      - PYTHONPATH=/app:/app/tool_sql-main
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Downstream service URLs (override defaults to correct Docker DNS names)
      - SQL_SERVICE_URL=http://tool-sql:7999/api/v1/agent
      - SEARCH_SERVICE_URL=http://vector-search:7997/search
      - CURRICULUM_SERVICE_URL=http://curriculum:7996/chat
      - MAPPING_SERVICE_URL=http://department-mapping:8000/map
      # - LLM_SERVICE_URL=http://llm-client:7998/agent  # llm-client service removed
    volumes:
      - ./ai_modules/llm_agent-main/logs:/app/logs
      - ./ai_modules/tool_sql-main:/app/tool_sql-main
      - ./ai_modules/llm_agent-main/processors:/app/processors
      - ./ai_modules/llm_agent-main/service:/app/service
      - ./ai_modules/llm_agent-main/tot:/app/tot
    ports:
      - "8001:8001"
    depends_on:
      - curriculum
      - vector-search
      # - llm-client  # service removed
      - tool-sql
      - department_mapping
    restart: unless-stopped

  # llm-client service removed - functionality integrated into llm_agent
  # llm-client:
  #   build:
  #     context: ./ai_modules/llm_agent-main
  #     dockerfile: Dockerfile
  #   container_name: llm-client
  #   environment:
  #     - PORT=7998
  #     - TZ=Asia/Seoul
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #   ports:
  #     - "7998:7998"
  #   restart: unless-stopped

  tool-sql:
    build:
      context: ./ai_modules/tool_sql-main
      dockerfile: Dockerfile
    container_name: tool-sql
    environment:
      - PORT=7999
      - TZ=Asia/Seoul
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=3313
      - DB_USER=root
      - DB_NAME=nll_third
      - DB_PASSWORD=${DB_PASSWORD}
      - VECTOR_DB_PASSWORD=${VECTOR_DB_PASSWORD}
    ports:
      - "7999:7999"
    restart: unless-stopped

  department_mapping:
    build:
      context: ./ai_modules/department_mapping-main
      dockerfile: Dockerfile
    container_name: department-mapping
    environment:
      - PORT=8000
      - TZ=Asia/Seoul
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./ai_modules/curriculum-main/result:/app/data
    restart: unless-stopped

  # Simple AI Mentor Frontend - DISABLED
  # simple_frontend:
  #   build:
  #     context: ./simple-frontend
  #     dockerfile: Dockerfile
  #   container_name: simple-frontend
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - TZ=Asia/Seoul
  #   depends_on:
  #     - llm_agent
  #   restart: unless-stopped

  # OpenWebUI (Main AI Mentor Interface)
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "8080:8080"  # Direct external access
    environment:
      - TZ=Asia/Seoul
      - PUBLIC_MODE=true
      - ENABLE_ADMIN_PANEL=false
      - RATE_LIMIT_RPM=60
      - WEBUI_AUTH=false
      - AUTHENTICATION=false
      - ENABLE_LOGIN=false
      - ENABLE_SIGNUP=false
      - ALLOW_ANONYMOUS=true
      - DISABLE_AUTH=true
      - BYPASS_MODEL_VALIDATION=true
      - DEFAULT_USER_ROLE=user
      - OPENAI_API_BASE_URL=http://llm-agent:8001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OLLAMA_BASE_URL=
      - ENABLE_OLLAMA_API=false
      - USE_OLLAMA_DOCKER=false
      - ENABLE_TITLE_GENERATION=false
      - ENABLE_TAGS_GENERATION=false
      - ENABLE_SEARCH=false
      - ENABLE_ADMIN=false
      - ENABLE_MODEL_FILTER=false
      - ENABLE_COMMUNITY_SHARING=false
      - ENABLE_USER_IMPORT=false
      - ENABLE_MESSAGE_RATING=false
      - ENABLE_WEB_SEARCH=false
      - ENABLE_RAG_WEB_SEARCH=false
      - SHOW_ADMIN_DETAILS=false
      - WEBUI_NAME=AI 멘토
      - DEFAULT_LOCALE=ko-KR
      - ENABLE_VOICE_CHAT=false
      - ENABLE_MESSAGING=false
      - AUDIO_STT_ENABLED=false
      - AUDIO_TTS_ENABLED=false
      - ENABLE_VOICE_INPUT=false
      - ENABLE_VOICE_OUTPUT=false
      - SHOW_VOICE_BUTTON=false
      - ENABLE_AUDIO_RECORDING=false
      - ENABLE_MIC_INPUT=false
      - TTS_ENABLED=false
      - STT_ENABLED=false
      - VOICE_INPUT_ENABLED=false
      - VOICE_OUTPUT_ENABLED=false
      - ENABLE_STT=false
      - ENABLE_TTS=false
      - SPEECH_TO_TEXT_ENABLED=false
      - TEXT_TO_SPEECH_ENABLED=false
      - ENABLE_FOLLOW_UP_QUESTIONS=false
      - SHOW_FOLLOW_UP_QUESTIONS=false
      - ENABLE_AUTO_SUGGESTIONS=false
      - SHOW_SUGGESTIONS=false
      - ENABLE_SUGGESTION_PROMPTS=false
      - ENABLE_RECOMMENDED_QUESTIONS=false
      - SHOW_RECOMMENDED_QUESTIONS=false
    volumes:
      - ./openwebui_new:/app/backend/data
      - ./custom-fix.css:/app/backend/static/custom.css:ro
    depends_on:
      - llm_agent
      - curriculum
      - vector-search
      # - llm-client  # service removed
      - tool-sql
    restart: unless-stopped
